fix: grep shouldn't trigger not found return code error
Signed-off-by: Steffen Tautenhahn <stevie-@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -66,6 +66,7 @@ runs:
         INPUT_PR_DRAFT: ${{ inputs.pr_draft }}
         INPUT_PR_ALLOW_EMPTY: ${{ inputs.pr_allow_empty }}
       id: pr-creation
+      shell: bash
       run: |
         set -e
         set -o pipefail
@@ -222,10 +223,10 @@ runs:
           set +e
           catch pr_command_output pr_command_error "${COMMAND[@]}"
           pr_command_exit_code=$?
+          pr_already_exists=$(echo "${pr_command_error}" | grep -c "already exists:" || true)
           set -e
           echo_info "Output of github cli command: " ${pr_command_output} ${pr_command_error}
 
-          pr_already_exists=$(echo "${pr_command_error}" | grep -c "already exists:")
           if [[ "$pr_command_exit_code" -eq 0 ]];
           then
             pr_url="${pr_command_output}"
@@ -252,11 +253,10 @@ runs:
         echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"
         echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
         echo "has_changed_files=${has_changed_files}" >> "$GITHUB_OUTPUT"
-        cat $GITHUB_OUTPUT
+        cat "$GITHUB_OUTPUT"
 
         echo "::endgroup::"
 
-      shell: bash
 
 branding:
   icon: 'git-pull-request'
